update folders structure
Inteli-College/2024-1B-T08-EC06-G03 pull request #133
Opened 2024-06-07 17:12 UTC by Gabrielle-Cartaxo

update folders structure

2024-06-07 17:12 UTC, Gabrielle-Cartaxo commented
Só coloquei o que estava na main até o dia 07/06/2024

2024-06-07 17:15 UTC, GuilhermeLinhares04 approved these changes

2024-06-09 16:57 UTC, ItsVasconcellos requested changes
Atualizar o pacote bolin na estrutura de pastas
<img src="https://media3.giphy.com/media/Zt2f45vHLZtaU/giphy.gif"/>

2024-06-09 16:57 UTC, ItsVasconcellos commented on README.md
> +            ┗ 📜build.sh
Deveria ter os pacotes que estão contidos dentro do /bolin/src, visto que eles são a principal parte dessa pasta

2024-06-11 01:57 UTC, merged