Bateria integrada no front + mock para testes
Inteli-College/2024-1B-T08-EC06-G03 pull request #183
Opened 2024-06-18 20:18 UTC by Gabrielle-Cartaxo

Eu trouxe para essa branch o mock alterado com as correções do @Eduardo-Barreto, pra conseguir testar. No vídeo abaixo é possível ver a bateria na tela fixada no canto superior direito, de acordo com o que está sendo publicado no tópico (no mockado, fixei em 50% a bateria).

[Gravação de tela de 18-06-2024 17:15:47.webm](https://github.com/Inteli-College/2024-1B-T08-EC06-G03/assets/123915876/af04df2f-b5ac-44a8-a2ff-9f1c3e0947ae)

(Inclusive, achei o mouse aparecia na gravação e fiquei apontando pras coisas mas não apareceu rs, mas foca na bateria ali no canto).

2024-06-18 20:19 UTC, Gabrielle-Cartaxo commented
Como as alterações da outra branch estão aqui, vou apagar a feat/battery

2024-06-19 18:21 UTC, ItsVasconcellos requested changes
Fiz algumas observações aqui, é mais questão de padronização de código para manter a qualidade mesmo.

2024-06-19 18:21 UTC, ItsVasconcellos commented on src/frontend/src/components/BatteryBar.tsx
> +      <p style={{ margin: 0, color: 'red' }}>{`${batteryLevel.toFixed(0)}%`}</p> {/* Estiliza o texto em vermelho */}
Acho que ficaria melhor se trocasse a cor de vermelho para branco, fica mais visível. Outra coisa é adicionar nas classes o `font-bold`

2024-06-19 18:21 UTC, ItsVasconcellos commented on src/frontend/src/components/BatteryBar.tsx
> +        />
Seria bom se aq fosse feito usando o tailwind para deixar as coisas mais padronizadas, foge o caso apenas a width com o `batteryLevel`

2024-06-19 18:21 UTC, ItsVasconcellos commented on src/frontend/src/App.tsx
> +
Idealmente alterar isso para que fique junto ao outra constante, uma vez que o websocket é o mesmo, só alterando a rota dele. basciamente ficaria as linhas 93 até a 103 só.

2024-06-19 19:14 UTC, Gabrielle-Cartaxo commented
Duvido olhar dnv @ItsVasconcellos

2024-06-19 19:47 UTC, ItsVasconcellos requested changes
só remover 

<img src="https://media1.giphy.com/media/xTiTnz33weTH3K8Uvu/giphy.gif"/>

2024-06-19 19:47 UTC, ItsVasconcellos commented on src/frontend/src/App.tsx
> +
remover

2024-06-19 19:57 UTC, Gabrielle-Cartaxo commented
YAAAAAAYYYYYYYYY

2024-06-19 19:57 UTC, merged