docs:methodology
Inteli-College/2024-1B-T08-EC06-G03 pull request #67
Opened 2024-05-09 21:00 UTC by Gabrielle-Cartaxo

Adicionei a metodologia que utilizamos para fazer o robô se mover

2024-05-09 22:07 UTC, Eduardo-Barreto requested changes
po abri pra ver e tava quebradinho, tem q ver oq eh isso aisufhasuifh

![image](https://github.com/Inteli-College/2024-1B-T08-EC06-G03/assets/34964398/511900ad-0137-40f5-b115-93d7fc870cc9)

2024-05-09 22:07 UTC, Eduardo-Barreto commented on docs/docs/Sprint 2/metodologia.md
> +Após essas mudanças, foi utilizado o colcon build e source install/local_setup.bash, finalizando assim a estruturação do workspace e do pacote.
```suggestion
Após essas mudanças, foi utilizado um script para compilar, executando source `run.sh`, finalizando assim a estruturação do workspace e do pacote.
```

2024-05-09 22:35 UTC, Gabrielle-Cartaxo commented
Resolvido!

2024-05-09 22:42 UTC, Eduardo-Barreto commented
Po aqui ainda não foi não... roda o docusaurus pra ver se ta rolando por aí antes

![image](https://github.com/Inteli-College/2024-1B-T08-EC06-G03/assets/34964398/321dc6d0-3a02-409e-903f-cd365e8855c5)

Eh de algum caracter especial em algum lugar provavelmente, da uma olhada aí

2024-05-10 13:36 UTC, Gabrielle-Cartaxo commented
Pô, aqui ta funfando:
![Captura de tela de 2024-05-10 10-34-51](https://github.com/Inteli-College/2024-1B-T08-EC06-G03/assets/123915876/09e7677d-4910-4ea2-a957-2b676f34bf39)

Vou reescrever essa linha 21 e me diz aí se abriu

2024-05-12 00:38 UTC, Eduardo-Barreto approved these changes
funcionou kkkkk se pa que era algum erro de parse na minha maquina mas fé fé

2024-05-13 00:58 UTC, Gabrielle-Cartaxo commented
O docusaurus não vai abrir agr pq eu coloquei o link pra uma imagem que não existe nessa branch, mas existe na main. Então, quando mergear, vai funcionar normal!

2024-05-13 03:13 UTC, merged