Feat/websocket camera
Inteli-College/2024-1B-T08-EC06-G03 pull request #84
Opened 2024-05-22 14:28 UTC by ItsVasconcellos

- toma websocket da camera funcionando com base64

<img src="https://media2.giphy.com/media/hryis7A55UXZNCUTNA/giphy.gif"/>

2024-05-22 14:33 UTC, Eduardo-Barreto requested changes
top, só arrumar esses detalhes e show

2024-05-22 14:33 UTC, Eduardo-Barreto commented on src/backend/api/controllers/camera.js
> +        // this.onClose = this.onClose.bind(this);
<img src="https://media3.giphy.com/media/CaiVJuZGvR8HK/giphy.gif"/>
isso aqui tem q ter amigao kkkkk eh legal ao menos logar qnd der ruim

2024-05-22 14:33 UTC, Eduardo-Barreto commented on src/backend/api/controllers/camera.js
> +        ws.on('close', () => this.onClose(ws));
do jeito que ta aqui, como vc não deu bind ele vai dar ruim qnd der erro ou der close iafushiaf pq ele n vai achar essas funções

2024-05-22 14:33 UTC, Eduardo-Barreto commented on src/backend/api/controllers/camera.js
> +      }
aqui acho que da pra verificar o `if (this.socket)` lá no começo e já meter um early return, pq se n tiver socket nem precisa encodar nada

2024-05-22 19:48 UTC, Eduardo-Barreto requested changes

2024-05-22 19:48 UTC, Eduardo-Barreto commented on src/backend/api/controllers/camera.js
> +        this.teleop_node = null;
am i a joke to you

2024-05-22 19:51 UTC, Eduardo-Barreto approved these changes
ta bala

2024-05-22 19:52 UTC, merged

2024-05-23 01:18 UTC, mauroDasChagas commented
Ai papai