Feat/camera
Inteli-College/2024-1B-T08-EC06-G03 pull request #85
Opened 2024-05-22 19:58 UTC by LuizaRubim

2024-05-23 20:35 UTC, ItsVasconcellos commented on src/bolin/src/bolin_camera/package.xml
> +
adiciona essas dependências aq 
```suggestion
  <build_depend>rclpy</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
```

2024-05-23 20:37 UTC, ItsVasconcellos requested changes
a vida não é morango, nem o pr. Tá faltando umas dependências ai, mas é suave de fazer 
<img src="https://media4.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

2024-05-24 13:56 UTC, mauroDasChagas commented
![image](https://github.com/Inteli-College/2024-1B-T08-EC06-G03/assets/123962654/9595f544-47f7-4d11-8d4f-c9ac113bf397)

2024-05-24 14:03 UTC, ItsVasconcellos approved these changes

2024-05-24 14:04 UTC, merged