add instructions to readme
Inteli-College/2024-1B-T08-EC06-G03 pull request #90
Opened 2024-05-22 20:35 UTC by LuizaRubim

2024-05-23 15:55 UTC, ItsVasconcellos approved these changes
é isso!!!

<img src="https://media3.giphy.com/media/AsAhDE4i9xLq4bjKJD/giphy.gif"/>

2024-05-23 19:45 UTC, ItsVasconcellos requested changes
talvez não seja bem isso ainda

<img src="https://media2.giphy.com/media/BDQmMy3ZM8sgRNFkhe/giphy.gif"/>

2024-05-23 19:45 UTC, ItsVasconcellos commented on README.md
> +    ```
-> Agora é build.sh e terá q rodar os pacotes:
ent: 
ros2 run pacote funcao 2x pq tem dois pacotes diferentes pra rodar

2024-05-23 20:36 UTC, LuizaRubim commented on README.md
> +    ```
são 3 pacotes (teleop, camera e lidar)

2024-05-24 14:14 UTC, ItsVasconcellos approved these changes
Tem que adicionar as instruções no readme.md

2024-05-24 14:24 UTC, merged